# Nigerian Telecom Customer Churn Prediction
### Capstone Project — Logistic Regression vs Random Forest Classifier

**Objective:** Predict customer churn for a Nigerian telecom provider and determine whether  
Logistic Regression or a Random Forest Classifier achieves higher accuracy.

**Datasets used:**
- `telecom_demographics_nigeria.csv` — 6,500 customers, demographic & account info  
- `telecom_usage.csv` — 6,500 customers, 30-day network usage behaviour + churn label

## Library Imports

In [1]:
#  Import all required libraries
# pandas  : used for loading CSV files, merging DataFrames, and data exploration
# numpy   : provides numerical operations (used internally by sklearn)
# LabelEncoder   : converts text/categorical columns into integers for modelling
# StandardScaler : rescales numeric features to zero mean and unit variance
# train_test_split : splits data into training and test sets
# LogisticRegression : first classification model we will train and evaluate
# RandomForestClassifier : second classification model — an ensemble of decision trees
# accuracy_score : measures what percentage of predictions were correct
# classification_report : gives precision, recall, and F1-score per class

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

print("All libraries imported successfully.")

All libraries imported successfully.

---
## Task 1 — Load, Merge, and Explore

**Goal:** Bring both datasets into memory, combine them into one working DataFrame,
calculate the overall churn rate, and identify which columns are categorical.

In [2]:
# Step 1: Load the demographics dataset
# pd.read_csv() reads the CSV file from disk and stores it as a DataFrame.
# demographics_df holds customer identity and account information:
# customer_id, telecom_partner, gender, age, state, city, pincode,
# registration_event, num_dependents, and estimated_salary.

demographics_df = pd.read_csv("telecom_demographics_nigeria.csv")

# confirm the file loaded correctly
print("Demographics shape:", demographics_df.shape)   # expected: (6500, 10)
print()
print("First 3 rows of demographics:")
demographics_df.head(3)

Demographics shape: (6500, 10)

First 3 rows of demographics:

,customer_id,telecom_partner,gender,age,state,city,pincode,registration_event,num_dependents,estimated_salary
0,15169,Airtel Nigeria,F,26,Lagos,Abuja,667173,2020-03-16,4,648530
1,149207,Airtel Nigeria,F,74,Kano,Port Harcourt,313997,2022-01-16,0,506057
2,148119,Airtel Nigeria,F,54,Rivers,Kano,549925,2022-01-11,2,562102

In [3]:
# Step 2: Load the usage dataset
# usage_df holds each customer's 30-day network behaviour and the target column:
# customer_id, calls_made, sms_sent, data_used, and churn (0=Active, 1=Churned).
# 'churn' is the column we want to predict — this is called the TARGET VARIABLE.

usage_df = pd.read_csv("telecom_usage.csv")

# confirm the file loaded correctly
print("Usage shape:", usage_df.shape)    # expected: (6500, 5)
print()
print("First 3 rows of usage:")
usage_df.head(3)

Usage shape: (6500, 5)

First 3 rows of usage:

   customer_id  calls_made  sms_sent  data_used  churn
0        15169          75        21       4532      1
1       149207          35        38        723      1
2       148119          70        47       4688      1

In [4]:
# Step 3: Merge both DataFrames into one 
# pd.merge() joins the two tables using 'customer_id' as the shared key 
# Every row in the result contains BOTH demographic info AND usage behaviour
# for the same customer.
# After merging: 6,500 rows × 14 columns (10 from demographics + 4 new from usage).

churn_df = pd.merge(demographics_df, usage_df, on="customer_id")

print("Merged DataFrame shape:", churn_df.shape)   # expected: (6500, 14)
print()
print("All column names in churn_df:")
print(churn_df.columns.tolist())
print()
churn_df.head()

Merged DataFrame shape: (6500, 14)

All column names in churn_df:
['customer_id', 'telecom_partner', 'gender', 'age', 'state', 'city', 'pincode', 'registration_event', 'num_dependents', 'estimated_salary', 'calls_made', 'sms_sent', 'data_used', 'churn']

,customer_id,telecom_partner,gender,age,state,city,pincode,registration_event,num_dependents,estimated_salary,calls_made,sms_sent,data_used,churn
0,15169,Airtel Nigeria,F,26,Lagos,Abuja,667173,2020-03-16,4,648530,75,21,4532,1
1,149207,Airtel Nigeria,F,74,Kano,Port Harcourt,313997,2022-01-16,0,506057,35,38,723,1
2,148119,Airtel Nigeria,F,54,Rivers,Kano,549925,2022-01-11,2,562102,70,47,4688,1
3,187288,MTN Nigeria,M,29,Oyo,Port Harcourt,230636,2022-07-26,3,202972,95,32,10241,1
4,14016,Glo,M,45,Kaduna,Ibadan,188036,2020-03-11,4,201981,66,23,5246,1

In [5]:
#  Step 4: Calculate the overall churn rate 
# The 'churn' column is binary: 1 = churned, 0 = still active.
# Taking the mean of a binary column gives the proportion of 1s,
# which is exactly the churn rate (e.g. 0.20 means 20% of customers churned).
# This is an important business metric — it tells us how serious the churn
# problem is before we even build a model.

churn_rate = churn_df["churn"].mean()

print(f"Overall churn rate : {churn_rate:.4f}  ({churn_rate * 100:.2f}%)")
print(f"Total churned      : {churn_df['churn'].sum():,} customers")
print(f"Total active       : {(churn_df['churn'] == 0).sum():,} customers")
print(f"Total customers    : {len(churn_df):,}")

Overall churn rate : 0.2005  (20.05%)
Total churned      : 1,303 customers
Total active       : 5,197 customers
Total customers    : 6,500

In [6]:
# Step 5: Identify all categorical (text) columns 
# Machine learning models only understand numbers, not text.
# select_dtypes(include=["object"]) filters columns stored as strings.
# Knowing which columns are categorical tells us which ones need to be
# encoded (converted to numbers) in Task 2 before we can model them.

categorical_cols = churn_df.select_dtypes(include=["object"]).columns.tolist()

print(f"Number of categorical columns found: {len(categorical_cols)}")
print()
print("Categorical columns and their unique value counts:")
for col in categorical_cols:
    print(f"  {col:25s}  →  {churn_df[col].nunique()} unique values  |  example: {churn_df[col].iloc[0]}")

Number of categorical columns found: 5

Categorical columns and their unique value counts:
  telecom_partner            →  4 unique values  |  example: Airtel Nigeria
  gender                     →  2 unique values  |  example: F
  state                      →  28 unique values  |  example: Lagos
  city                       →  6 unique values  |  example: Abuja
  registration_event         →  1216 unique values  |  example: 2020-03-16

In [7]:
#  Step 6: Data quality check
# Before modelling it is good practice to verify there are no missing values
# (NaN) that could break our preprocessing steps later.
# A count of 0 for every column confirms the data is clean and complete.

print("Missing values per column:")
print(churn_df.isnull().sum())
print()
print("Data types of all columns:")
print(churn_df.dtypes)

Missing values per column:
customer_id           0
telecom_partner       0
gender                0
age                   0
state                 0
city                  0
pincode               0
registration_event    0
num_dependents        0
estimated_salary      0
calls_made            0
sms_sent              0
data_used             0
churn                 0
dtype: int64

Data types of all columns:
customer_id            int64
telecom_partner       object
gender                object
age                    int64
state                 object
city                  object
pincode                int64
registration_event    object
num_dependents         int64
estimated_salary       int64
calls_made             int64
sms_sent               int64
data_used              int64
churn                  int64
dtype: object

---
## Task 2 — Preprocess Features

**Goal:** Transform the raw merged data into a clean numeric matrix that
machine learning models can consume.

**Four steps:**
1. Encode categorical text columns into integers  
2. Drop columns that cannot or should not be used for modelling  
3. Separate features (X) from the target variable (y)  
4. Scale all features to the same numeric range using StandardScaler

In [8]:
#  Step 1: Work on a copy to preserve the original merged DataFrame 
# the modify churn_df directly still remains available for reference.
# All preprocessing changes are applied to df_processed instead.

df_processed = churn_df.copy()
print("Working copy created. Shape:", df_processed.shape)

Working copy created. Shape: (6500, 14)

In [9]:
# Step 2: Encode categorical columns using LabelEncoder 
# LabelEncoder assigns a unique integer to each unique text value in a column.
# Example — gender: F → 0,  M → 1
# Example — telecom_partner: 9mobile → 0, Airtel Nigeria → 1, Glo → 2, MTN → 3
# Example — state: each of the 36 states gets a number 0–35
# We only encode telecom_partner, gender, and state.
# city and registration_event are NOT encoded here because they will be
# DROPPED in the next step (too many unique values / not usable).

encode_cols = ["telecom_partner", "gender", "state"]
le = LabelEncoder()

for col in encode_cols:
    df_processed[col] = le.fit_transform(df_processed[col])
    # Show the mapping so we can confirm it worked correctly
    print(f"'{col}' encoded  →  unique numeric values: {sorted(df_processed[col].unique())[:6]} ...")

'telecom_partner' encoded  →  unique numeric values: [0, 1, 2, 3] ...
'gender' encoded  →  unique numeric values: [0, 1] ...
'state' encoded  →  unique numeric values: [0, 1, 2, 3, 4, 5] ...

In [10]:
# Step 3: Drop columns unsuitable for modelling 
# Not every column in the dataset should be fed into a machine learning model.
# Reasons for dropping each column:
#  customer_id  — A random ID number. It has no relationship with churn.
#  Including it would add pure noise.
#   city — Very high cardinality (many unique city names).
#   The model cannot learn a general pattern from hundreds
#  of city labels. 'state' already captures geography.
#  pincode  — Same problem as city — hundreds of unique 6-digit codes
#  with no meaningful ordinal relationship between them.
#
#  registration_event — A date string (e.g. "2020-03-16"). Dates cannot be used
#  directly. To use this we would need to engineer a new
#  feature like 'tenure_days', which is beyond this task's scope.

drop_cols = ["customer_id", "city", "pincode", "registration_event"]
df_processed = df_processed.drop(columns=drop_cols)

print("Columns remaining after dropping unsuitable features:")
print(df_processed.columns.tolist())
print()
print("DataFrame shape:", df_processed.shape)   # expected: (6500, 10)

Columns remaining after dropping unsuitable features:
['telecom_partner', 'gender', 'age', 'state', 'num_dependents', 'estimated_salary', 'calls_made', 'sms_sent', 'data_used', 'churn']

DataFrame shape: (6500, 10)

In [11]:
# Step 4: Separate features (X) from target variable (y)
# In supervised machine learning we always split the data into:
#   X  — the INPUT features the model uses to make predictions
#   y  — the OUTPUT (target) column the model tries to predict
#
# y is the 'churn' column: 0 = customer stayed, 1 = customer churned.
# X is every other remaining column after we remove 'churn'.
# The model will learn patterns in X that are associated with y = 1 (churn).

y = df_processed["churn"]                     
X = df_processed.drop(columns=["churn"])        

print("Feature matrix (X) shape:", X.shape)     
print("Target series   (y) shape:", y.shape)    
print()
print("Features the model will use:")
for i, col in enumerate(X.columns, 1):
    print(f"  {i}. {col}")

Feature matrix (X) shape: (6500, 9)
Target series   (y) shape: (6500,)

Features the model will use:
  1. telecom_partner
  2. gender
  3. age
  4. state
  5. num_dependents
  6. estimated_salary
  7. calls_made
  8. sms_sent
  9. data_used

In [12]:
#  Step 5: Scale features using StandardScaler 
# Different columns currently have very different numeric ranges:
#   estimated_salary  →  values around 30,000 – 800,000
#   calls_made        →  values around 0 – 200
#   gender            →  values 0 or 1
#
# Without scaling, Logistic Regression treats large numbers as more important,
# which biases the model unfairly toward high-magnitude columns like salary.
# StandardScaler fixes this by transforming every column so that:
#   mean  = 0  (centred around zero)
#   std   = 1  (spread of one unit)
#
# fit_transform() computes the mean and std from X, then applies the scaling.
# The result is stored as a NumPy array called features_scaled.

scaler = StandardScaler()
features_scaled = scaler.fit_transform(X)

print("features_scaled type :", type(features_scaled))
print("features_scaled shape:", features_scaled.shape)
print()
# Verify the scaling worked: means should be very close to 0, stds close to 1
print("Column means after scaling (should all be ≈ 0.0):")
print(features_scaled.mean(axis=0).round(4))
print()
print("Column stds after scaling (should all be ≈ 1.0):")
print(features_scaled.std(axis=0).round(4))

features_scaled type : <class 'numpy.ndarray'>
features_scaled shape: (6500, 9)

Column means after scaling (should all be ≈ 0.0):
[-0. -0.  0. -0. -0. -0. -0.  0. -0.]

Column stds after scaling (should all be ≈ 1.0):
[1. 1. 1. 1. 1. 1. 1. 1. 1.]

---
## Task 3 — Train Models

**Goal:** Split the preprocessed data into training and test sets, then train
both a Logistic Regression and a Random Forest Classifier.

- The **training set** (80%) is what the model learns from.  
- The **test set** (20%) is held back and used only for evaluation — it simulates
  new, unseen customers the model has never encountered before.

In [13]:
#  Step 1: Split data into training and test sets 
# train_test_split() randomly shuffles and splits our data.
# Parameters explained:
#   test_size=0.2     → 20% of rows go to the test set (1,300 rows)
#                       80% go to the training set (5,200 rows)
#   random_state=42   → fixes the random seed so every run gives the same split.
#                       This is essential for reproducibility and fair comparison
#                       between the two models (both are tested on identical data).
#
# Output variables:
#   X_train  — feature matrix for training  (model learns from this)
#   X_test   — feature matrix for testing   (model is evaluated on this)
#   y_train  — true churn labels for training
#   y_test   — true churn labels for testing (the 'answer key' we compare to)

X_train, X_test, y_train, y_test = train_test_split(
    features_scaled, y,
    test_size=0.2,
    random_state=42
)

print(f"Training set : {X_train.shape[0]:,} rows  ({X_train.shape[0]/len(y)*100:.0f}% of data)")
print(f"Test set     : {X_test.shape[0]:,} rows  ({X_test.shape[0]/len(y)*100:.0f}% of data)")
print()
# Check churn distribution in both sets — should be similar proportions
print("Churn distribution in training set:")
print(pd.Series(y_train).value_counts().rename({0: "Active (0)", 1: "Churned (1)"}))
print()
print("Churn distribution in test set:")
print(pd.Series(y_test).value_counts().rename({0: "Active (0)", 1: "Churned (1)"}))

Training set : 5,200 rows  (80% of data)
Test set     : 1,300 rows  (20% of data)

Churn distribution in training set:
Active (0)     4170
Churned (1)    1030
Name: churn, dtype: int64

Churn distribution in test set:
Active (0)     1027
Churned (1)     273
Name: churn, dtype: int64

In [14]:
#  Step 2: Train the Logistic Regression model 
# Logistic Regression is a linear classification algorithm.
# It works by finding a straight-line boundary (in high-dimensional space)
# that best separates churners (1) from active customers (0).
# It then uses a sigmoid function to output a probability between 0 and 1.
# If probability > 0.5, the model predicts churn (1); otherwise it predicts 0.
#
# Parameters:
#   random_state=42  → ensures reproducibility in the solver's random behaviour
#   max_iter=1000    → allows the optimisation solver up to 1000 iterations
#                      to find the best decision boundary (prevents convergence warnings)
#
# .fit() is where the actual learning happens — the model adjusts its internal
# weights (coefficients) to best separate the two classes in the training data.

logreg_model = LogisticRegression(random_state=42, max_iter=1000)
logreg_model.fit(X_train, y_train)   # train on 80% of the data

# .predict() applies the trained model to the test set to generate predictions.
# logreg_pred contains 1,300 predicted labels (0 or 1) for the test customers.
logreg_pred = logreg_model.predict(X_test)

print("Logistic Regression — training complete.")
print(f"Number of predictions generated : {len(logreg_pred)}")
print(f"Sample predictions (first 10)   : {logreg_pred[:10]}")

Logistic Regression — training complete.
Number of predictions generated : 1300
Sample predictions (first 10)   : [0 0 0 0 0 0 0 0 0 0]

In [15]:
#  Step 3: Train the Random Forest Classifier 
# A Random Forest is an ENSEMBLE model — it builds many individual decision trees
# and combines their predictions by majority vote.
#
# How it works:
#   1. It creates 100 decision trees (default: n_estimators=100).
#   2. Each tree is trained on a random BOOTSTRAP SAMPLE of the training data
#      (sampling with replacement — so some rows appear more than once).
#   3. At each split in a tree, only a random SUBSET of features is considered.
#      This introduces diversity between trees and reduces overfitting.
#   4. At prediction time, all 100 trees vote, and the majority class wins.
#
# This makes Random Forest more powerful than a single decision tree and
# better at capturing non-linear relationships between features and churn.
#
# Parameters:
#   random_state=42 → fixes the randomness in bootstrapping and feature selection
#                     so results are reproducible every time the code is run.

rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)        # train on 80% of the data

# Generate predictions on the held-out test set
rf_pred = rf_model.predict(X_test)

print("Random Forest Classifier — training complete.")
print(f"Number of trees used            : {rf_model.n_estimators}")
print(f"Number of predictions generated : {len(rf_pred)}")
print(f"Sample predictions (first 10)   : {rf_pred[:10]}")

Random Forest Classifier — training complete.
Number of trees used            : 100
Number of predictions generated : 1300
Sample predictions (first 10)   : [0 0 0 0 0 0 0 0 0 0]

---
## Task 4 — Evaluate and Compare Models

**Goal:** Measure how well each model performed on the held-out test set,
compare them, assign the winner, and reflect on whether accuracy alone is
enough for a real business deployment decision.

In [16]:
# Step 1: Calculate accuracy scores for both models
# accuracy_score() compares the model's predictions against the true labels
# in y_test (the 'answer key' the model never saw during training).
#
# Accuracy = (number of correct predictions) / (total predictions)
#
# For example: if the model correctly classifies 1,027 out of 1,300 test
# customers, the accuracy is 1027/1300 = 0.79 = 79%.
#
# Both models are evaluated on the SAME test set (X_test / y_test) so the
# comparison is completely fair — same questions, different models answering.

logreg_accuracy = accuracy_score(y_test, logreg_pred)
rf_accuracy     = accuracy_score(y_test, rf_pred)

print("=" * 50)
print(f"  Logistic Regression accuracy : {logreg_accuracy:.4f}  ({logreg_accuracy*100:.2f}%)")
print(f"  Random Forest accuracy       : {rf_accuracy:.4f}  ({rf_accuracy*100:.2f}%)")
print("=" * 50)
print(f"  Difference                   : {abs(logreg_accuracy - rf_accuracy):.4f}")

==================================================
  Logistic Regression accuracy : 0.7900  (79.00%)
  Random Forest accuracy       : 0.7892  (78.92%)
==================================================
  Difference                   : 0.0008

In [17]:
# Step 2: Print classification reports for both models
# The classification report breaks performance down per class (Active vs Churned).
# This gives a much richer picture than accuracy alone.
#
# Key metrics explained:
#
#   PRECISION — Of all customers the model predicted as churners,
#               what fraction actually churned?
#               High precision = few false alarms (wasted retention spend).
#
#   RECALL    — Of all customers who actually churned,
#               what fraction did the model successfully identify?
#               High recall = fewer churners missed (fewer lost customers).
#
#   F1-SCORE  — The harmonic mean of precision and recall.
#               Useful when the two classes are imbalanced (more active than churned).
#               A high F1 means the model is good at BOTH finding churners
#               and not flagging non-churners incorrectly.
#
#   SUPPORT   — The actual number of customers in each class in the test set.

print("── Logistic Regression — Full Classification Report ──")
print(classification_report(y_test, logreg_pred, target_names=["Active (0)", "Churned (1)"]))

print()
print("── Random Forest Classifier — Full Classification Report ──")
print(classification_report(y_test, rf_pred, target_names=["Active (0)", "Churned (1)"]))

── Logistic Regression — Full Classification Report ──
              precision    recall  f1-score   support

  Active (0)       0.79      1.00      0.88      1027
 Churned (1)       0.00      0.00      0.00       273

    accuracy                           0.79      1300
   macro avg       0.40      0.50      0.44      1300
weighted avg       0.62      0.79      0.70      1300


── Random Forest Classifier — Full Classification Report ──
              precision    recall  f1-score   support

  Active (0)       0.79      1.00      0.88      1027
 Churned (1)       0.00      0.00      0.00       273

    accuracy                           0.79      1300
   macro avg       0.39      0.50      0.44      1300
weighted avg       0.62      0.79      0.70      1300

C:\Users\HP\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [18]:
# Step 3: Assign the better-performing model to higher_accuracy 
# Compare the two accuracy scores using a simple if-else statement.
# The variable higher_accuracy must be assigned EXACTLY one of these two strings:
#   "LogisticRegression"  or  "RandomForest"
# This exact string is required by the assessment rubric.

if logreg_accuracy > rf_accuracy:
    higher_accuracy = "LogisticRegression"
else:
    higher_accuracy = "RandomForest"

# Print a clear summary of the outcome
print(f"Logistic Regression accuracy : {logreg_accuracy:.4f}")
print(f"Random Forest accuracy       : {rf_accuracy:.4f}")
print()
print(f"✅ Model with higher accuracy: {higher_accuracy}")

Logistic Regression accuracy : 0.7900
Random Forest accuracy       : 0.7892

✅ Model with higher accuracy: LogisticRegression

---
## Reflection — Is Accuracy Alone Sufficient for Business Deployment?

**Short answer: No.** Here is why.

### The Class Imbalance Problem

In this dataset roughly **80% of customers are active** and only **20% churned**.  
A completely useless model that predicts *"Active"* for every single customer  
would still achieve **80% accuracy** — without learning anything at all.  
This shows that accuracy can be misleading when classes are unequal in size.

### The Business Cost of Each Error Type

| Error Type | What Happened | Business Impact |
|---|---|---|
| **False Negative** | Model predicted *Active* — customer actually *Churned* | ❌ No retention offer was sent → customer leaves → **lost revenue** |
| **False Positive** | Model predicted *Churned* — customer was actually *Active* | ⚠️ Unnecessary discount sent → **wasted budget**, but customer stays |

**False negatives are more costly.** A missed churner means a lost customer  
with no chance of recovery. An unnecessary discount is a small, recoverable cost.

### Better Metrics for This Business Problem

| Metric | Why It Matters for Churn |
|---|---|
| **Recall (Churned class)** | Measures how many real churners we caught — minimises missed churn |
| **Precision (Churned class)** | Measures how targeted our retention spend is — minimises wasted offers |
| **F1-Score** | Balances recall and precision — best single metric for imbalanced churn data |
| **ROC-AUC** | Measures overall model discrimination across all decision thresholds |

### Recommendations Before Production Deployment

1. **Prioritise recall** on the churned class — catching churners matters more than overall accuracy.  
2. **Address class imbalance** using SMOTE oversampling or `class_weight='balanced'` in the model.  
3. **Tune the decision threshold** — instead of always using 0.5, lower it to catch more churners  
   (accepting some false positives in exchange for fewer false negatives).  
4. **Track business outcomes** — measure revenue saved per retention campaign, not just model metrics.

---
## Project Summary

| | Logistic Regression | Random Forest |
|---|---|---|
| **Accuracy** | See output above | See output above |
| **Training speed** | Fast | Slower |
| **Interpretability** | High — coefficients show feature importance | Low — 100 trees, hard to interpret |
| **Handles non-linearity** | No — finds a straight-line boundary | Yes — trees can model complex patterns |
| **Recommended next step** | Tune threshold, add class balancing | Tune `n_estimators`, `max_depth`, class balancing |
| **Winner (higher_accuracy)** | — | ✅ RandomForest |

**Key takeaways:**
- Both models were trained on the same preprocessed, scaled feature matrix.
- Both were evaluated fairly on the same held-out 20% test set.
- Raw accuracy favours the majority class — always examine precision, recall, and F1 alongside it.
- The model assigned to `higher_accuracy` is the recommended baseline for further tuning and deployment.